[package]
name = "minstall"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scraper = "0.14.0"
reqwest = {version = "0.11", features = ["blocking"]}
trauma = "2.2.2"
tokio = "1.28.0"
